/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:Wolves:683552:
  println("Wolves - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Wolves:683552:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Flamingo:326798:
  println("Flamingo - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Flamingo:326798:

public void button1_click3(GButton source, GEvent event) { //_CODE_:PolarBear:665517:
  println("PolarBear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:PolarBear:665517:

public void button1_click4(GButton source, GEvent event) { //_CODE_:Lion:834870:
  println("Lion - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Lion:834870:

public void button1_click5(GButton source, GEvent event) { //_CODE_:Panda:529088:
  println("Panda - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Panda:529088:

public void button1_click6(GButton source, GEvent event) { //_CODE_:Bear:379431:
  println("Bear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Bear:379431:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Wolves = new GButton(this, 103, 35, 50, 50);
  Wolves.setText("Wolf");
  Wolves.addEventHandler(this, "button1_click1");
  Flamingo = new GButton(this, 579, 409, 50, 50);
  Flamingo.setText("Flamingo");
  Flamingo.addEventHandler(this, "button1_click2");
  PolarBear = new GButton(this, 464, 311, 50, 50);
  PolarBear.setText("Polar Bear");
  PolarBear.addEventHandler(this, "button1_click3");
  Lion = new GButton(this, 356, 418, 50, 50);
  Lion.setText("Lion");
  Lion.addEventHandler(this, "button1_click4");
  Panda = new GButton(this, 72, 262, 50, 50);
  Panda.setText("Panda");
  Panda.addEventHandler(this, "button1_click5");
  Bear = new GButton(this, 369, 167, 80, 30);
  Bear.setText("Face text");
  Bear.addEventHandler(this, "button1_click6");
}

// Variable declarations 
// autogenerated do not edit
GButton Wolves; 
GButton Flamingo; 
GButton PolarBear; 
GButton Lion; 
GButton Panda; 
GButton Bear; 
