/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:Wolves:683552:
  println("Wolves - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Wolves:683552:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Flamingo:326798:
  println("Flamingo - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Flamingo:326798:

public void button1_click3(GButton source, GEvent event) { //_CODE_:PolarBear:665517:
  println("PolarBear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:PolarBear:665517:

public void button1_click4(GButton source, GEvent event) { //_CODE_:Lion:834870:
  println("Lion - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Lion:834870:

public void button1_click5(GButton source, GEvent event) { //_CODE_:Panda:529088:
  println("Panda - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Panda:529088:

public void button1_click6(GButton source, GEvent event) { //_CODE_:Bear:379431:
  println("Bear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Bear:379431:

public void button1_click7(GButton source, GEvent event) { //_CODE_:Deer:661191:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Deer:661191:

public void button1_click8(GButton source, GEvent event) { //_CODE_:Seel:952336:
  println("Seel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Seel:952336:

public void button1_click9(GButton source, GEvent event) { //_CODE_:Bat:265536:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Bat:265536:

public void button1_click10(GButton source, GEvent event) { //_CODE_:Baboon:753847:
  println("Baboon - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Baboon:753847:

public void button1_click11(GButton source, GEvent event) { //_CODE_:Kamel:333613:
  println("Kamel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Kamel:333613:

public void button1_click12(GButton source, GEvent event) { //_CODE_:LarGibbon:833434:
  println("LarGibbon - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:LarGibbon:833434:

public void button1_click13(GButton source, GEvent event) { //_CODE_:Lemur:948172:
  println("Lemur - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Lemur:948172:

public void button1_click14(GButton source, GEvent event) { //_CODE_:Stork:992027:
  println("Stork - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Stork:992027:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Wolves = new GButton(this, 132, 39, 50, 50);
  Wolves.setText("Wolf");
  Wolves.addEventHandler(this, "button1_click1");
  Flamingo = new GButton(this, 729, 446, 50, 50);
  Flamingo.setText("Flamingo");
  Flamingo.addEventHandler(this, "button1_click2");
  PolarBear = new GButton(this, 582, 333, 50, 50);
  PolarBear.setText("Polar Bear");
  PolarBear.addEventHandler(this, "button1_click3");
  Lion = new GButton(this, 453, 455, 50, 50);
  Lion.setText("Lion");
  Lion.addEventHandler(this, "button1_click4");
  Panda = new GButton(this, 98, 289, 50, 50);
  Panda.setText("Panda");
  Panda.addEventHandler(this, "button1_click5");
  Bear = new GButton(this, 411, 123, 50, 50);
  Bear.setText("Bear");
  Bear.addEventHandler(this, "button1_click6");
  Deer = new GButton(this, 255, 205, 50, 50);
  Deer.setText("Deer");
  Deer.addEventHandler(this, "button1_click7");
  Seel = new GButton(this, 255, 305, 50, 50);
  Seel.setText("Seel");
  Seel.addEventHandler(this, "button1_click8");
  Bat = new GButton(this, 382, 338, 50, 50);
  Bat.setText("Bat");
  Bat.addEventHandler(this, "button1_click9");
  Baboon = new GButton(this, 443, 339, 50, 50);
  Baboon.setText("Baboon");
  Baboon.addEventHandler(this, "button1_click10");
  Kamel = new GButton(this, 420, 630, 50, 50);
  Kamel.setText("Kamel");
  Kamel.addEventHandler(this, "button1_click11");
  LarGibbon = new GButton(this, 81, 508, 50, 50);
  LarGibbon.setText("LarGibbon");
  LarGibbon.addEventHandler(this, "button1_click12");
  Lemur = new GButton(this, 857, 442, 50, 50);
  Lemur.setText("Lemur");
  Lemur.addEventHandler(this, "button1_click13");
  Stork = new GButton(this, 857, 285, 50, 50);
  Stork.setText("Stork");
  Stork.addEventHandler(this, "button1_click14");
}

// Variable declarations 
// autogenerated do not edit
GButton Wolves; 
GButton Flamingo; 
GButton PolarBear; 
GButton Lion; 
GButton Panda; 
GButton Bear; 
GButton Deer; 
GButton Seel; 
GButton Bat; 
GButton Baboon; 
GButton Kamel; 
GButton LarGibbon; 
GButton Lemur; 
GButton Stork; 
